# Generated by Django 4.2.5 on 2023-12-11 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='cover_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
